void setup() {		// the setup function runs once
  Serial.begin(9600); // open serial communication
  Serial.println(“hello!”);
  delay(1000);  
}
void loop() {  //ignore the 'void loop()' for this one…
  Serial.println(“we are friends…”);  
  delay(1000); //ignore this...
}              //ignore this...